apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-test
spec:
  replicas: 3
  selector:
    app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx

